"""
Authentication logic: store signup and login.

This module owns the store-login identity path only. Super Admin
authentication is intentionally handled by a separate module
(core/admin_auth.py, built later) against a separate database table -
not by a flag or branch in this file - so that a bug here can never
become a path to admin access.

All functions here either return a meaningful success value or raise a
specific exception from core.exceptions. Nothing in this module returns
None/False to signal failure, so calling code is never left guessing
whether a falsy return means "invalid" or "not yet checked".
"""

import bcrypt

from core.database import get_connection
from core.exceptions import DuplicateMobileError, InvalidCredentialsError, DatabaseError
from utils.validators import validate_mobile_number, validate_password, validate_required_text


def _hash_password(plain_password: str) -> str:
    """Hash a plaintext password using bcrypt.

    bcrypt is chosen over a faster hash (e.g. SHA-256) deliberately:
    it's designed to be slow, which makes brute-force password guessing
    expensive even if the database is ever compromised. Each hash
    includes its own randomly generated salt, so two stores with the
    same password never produce the same hash.

    Args:
        plain_password: The password as entered by the user.

    Returns:
        A bcrypt hash string, safe to store in the database.
    """
    salt = bcrypt.gensalt()
    hashed = bcrypt.hashpw(plain_password.encode("utf-8"), salt)
    return hashed.decode("utf-8")


def _verify_password(plain_password: str, password_hash: str) -> bool:
    """Check a plaintext password against a stored bcrypt hash.

    Args:
        plain_password: The password as entered by the user at login.
        password_hash: The bcrypt hash stored in the database.

    Returns:
        True if the password matches, False otherwise.
    """
    return bcrypt.checkpw(plain_password.encode("utf-8"), password_hash.encode("utf-8"))


def signup(store_name: str, owner_name: str, mobile_number: str, password: str) -> int:
    """Register a new medical store account.

    Validates all inputs, checks mobile number uniqueness, hashes the
    password, and creates the store row. The store_id (primary key) is
    auto-generated by SQLite - callers never supply or choose it, which
    is the deliberate design so a store never has to remember or type an
    ID.

    Args:
        store_name: Name of the medical store.
        owner_name: Name of the store owner.
        mobile_number: Owner's mobile number, any common input format.
        password: Plaintext password chosen by the owner (6-20 chars).

    Returns:
        The newly created store_id.

    Raises:
        ValidationError: If any field fails validation.
        DuplicateMobileError: If the mobile number is already registered.
        DatabaseError: If the database operation fails for any other
            reason.
    """
    clean_store_name = validate_required_text(store_name, "Store Name")
    clean_owner_name = validate_required_text(owner_name, "Owner Name")
    clean_mobile_number = validate_mobile_number(mobile_number)
    validate_password(password)

    password_hash = _hash_password(password)

    try:
        with get_connection() as connection:
            cursor = connection.execute(
                """
                INSERT INTO stores (store_name, owner_name, mobile_number, password_hash)
                VALUES (?, ?, ?, ?)
                """,
                (clean_store_name, clean_owner_name, clean_mobile_number, password_hash),
            )
            return cursor.lastrowid
    except DatabaseError as error:
        # sqlite3.IntegrityError (wrapped as DatabaseError by get_connection)
        # is raised when the UNIQUE constraint on mobile_number is violated.
        # Checking the message is a pragmatic MVP approach; if this needs
        # to be more robust later, get_connection could be extended to
        # preserve the original sqlite3 exception type for inspection.
        if "UNIQUE constraint failed" in str(error):
            raise DuplicateMobileError(
                "This mobile number is already registered. Please login instead."
            ) from error
        raise


def login(mobile_number: str, password: str) -> dict:
    """Authenticate a store owner by mobile number and password.

    Deliberately raises the same InvalidCredentialsError whether the
    mobile number doesn't exist or the password is wrong - distinguishing
    the two would let an attacker check which mobile numbers are
    registered on the platform.

    Args:
        mobile_number: Mobile number as entered at login, any common
            input format.
        password: Plaintext password as entered at login.

    Returns:
        A dict with keys "store_id", "store_name", "owner_name" for the
        authenticated store.

    Raises:
        ValidationError: If the mobile number format is invalid.
        InvalidCredentialsError: If the mobile number and password
            combination does not match any account.
    """
    clean_mobile_number = validate_mobile_number(mobile_number)

    with get_connection() as connection:
        row = connection.execute(
            """
            SELECT store_id, store_name, owner_name, password_hash
            FROM stores
            WHERE mobile_number = ?
            """,
            (clean_mobile_number,),
        ).fetchone()

    if row is None or not _verify_password(password, row["password_hash"]):
        raise InvalidCredentialsError("Invalid mobile number or password.")

    return {
        "store_id": row["store_id"],
        "store_name": row["store_name"],
        "owner_name": row["owner_name"],
    }
