"""
Product Management screen UI.

Provides View, Search, Edit, and Delete (per the project's module spec)
plus Add, since a list with no way to add to it isn't useful on its own
and the spec's Database module already calls for "automatically save
extracted products" - manual add is the non-OCR equivalent of that same
need.

Form fields are generated by looping over config.product_schema.PRODUCT_FIELDS
rather than hardcoding one st.text_input call per field. This is what
makes "no medical-specific hardcoding" real in the UI layer, not just in
the database: adding or changing a field in product_schema.py changes
this form automatically, with no edits needed here.
"""

from datetime import date, datetime

import streamlit as st

from modules.products import service as products_service
from config.product_schema import PRODUCT_FIELDS, FieldType
from core.session import get_current_store_id
from core.exceptions import ValidationError
from core.cache_utils import get_cache_epoch, bump_cache_epoch


def render_products_page() -> None:
    """Render the Product Management screen: search/list, add, edit,
    and delete, in a single screen with tabs to keep navigation minimal
    per the project's UI rules.
    """
    st.subheader("💊 Product Management")

    list_tab, add_tab = st.tabs(["View / Search Products", "Add New Product"])

    with list_tab:
        _render_product_list()

    with add_tab:
        _render_add_product_form()


@st.cache_data(show_spinner=False)
def _search_products_cached(store_id: int, search_term: str, _epoch: int) -> list:
    return products_service.search_products(store_id, search_term)

def _render_product_list() -> None:
    """Render the searchable product list with edit/delete actions per
    row.
    """
    store_id = get_current_store_id()

    search_col, search_btn_col = st.columns([6, 1.3])

    with search_col:
        search_term = st.text_input(
            "Search by medicine name or batch number",
            placeholder="e.g. Paracetamol or B001",
            key="products_search_term",
        )
    
    with search_btn_col:
        st.button(
            "🔎 Search",
            key="products_search_button",
            type="primary",
            use_container_width=True,
        )
    
    products = _search_products_cached(
        store_id,
        search_term,
        get_cache_epoch(),
    )
    if not products:
        if search_term:
            st.info("No products match your search.")
        else:
            st.info("No products yet. Add your first product in the 'Add New Product' tab.")
        return

    st.caption(f"{len(products)} product(s)")

    for product in products:
        _render_product_row(store_id, product)


def _render_product_row(store_id: int, product: dict) -> None:
    """Render a single product as an expandable row with edit and
    delete actions.

    Each row is its own expander rather than one big table, since a
    table with 9 columns would be unreadable on a phone screen - this
    keeps the row compact when collapsed (name, batch, quantity at a
    glance) and full detail/actions available on tap, consistent with
    "minimal clicks, mobile-friendly" UI rules.
    """
    summary = (
        f"{product['name']}  •  Batch: {product['batch_number']}  •  "
        f"Qty: {product['quantity']}  •  Expires: {product['expiry_date']}  •  "
        f"MRP: {product['mrp']}  •  Rate: {product['rate']}"
    )

    with st.expander(summary):
        edit_key = f"editing_product_{product['product_id']}"

        if st.session_state.get(edit_key):
            _render_edit_form(store_id, product)
        else:
            col1, col2 = st.columns(2)
            with col1:
                if st.button("✏️ Edit", key=f"edit_btn_{product['product_id']}", use_container_width=True):
                    st.session_state[edit_key] = True
                    st.rerun()
            with col2:
                _render_delete_button(store_id, product)


def _render_delete_button(store_id: int, product: dict) -> None:
    """Render a delete button with a confirmation step.

    A two-step confirm (click once to arm, click again to actually
    delete) prevents an accidental tap from permanently removing a
    product - a real risk on a touchscreen where rows are close
    together, and deletion has no undo in this MVP.
    """
    confirm_key = f"confirm_delete_{product['product_id']}"

    if not st.session_state.get(confirm_key):
        if st.button("🗑️ Delete", key=f"delete_btn_{product['product_id']}", use_container_width=True):
            st.session_state[confirm_key] = True
            st.rerun()
    else:
        st.warning(f"Delete '{product['name']}'? This cannot be undone.")
        confirm_col, cancel_col = st.columns(2)
        with confirm_col:
            if st.button("Yes, Delete", key=f"confirm_yes_{product['product_id']}", use_container_width=True):
                try:
                    products_service.remove_product(store_id, product["product_id"])
                    bump_cache_epoch()
                    st.session_state.pop(confirm_key, None)
                    st.success(f"'{product['name']}' deleted.")
                    st.rerun()
                except ValidationError as error:
                    st.error(str(error))
        with cancel_col:
            if st.button("Cancel", key=f"confirm_no_{product['product_id']}", use_container_width=True):
                st.session_state.pop(confirm_key, None)
                st.rerun()


def _render_edit_form(store_id: int, product: dict) -> None:
    """Render an inline edit form pre-filled with the product's current
    values.
    """
    edit_key = f"editing_product_{product['product_id']}"
    field_key_prefix = f"edit_{product['product_id']}"

    # Rendered before st.form opens, deliberately: see
    # _render_custom_threshold_checkbox's docstring for why this
    # checkbox cannot live inside the form and still update the number
    # input below it on the same interaction.
    custom_threshold_enabled = _render_custom_threshold_checkbox(
        existing_value=product.get("minimum_stock_threshold"),
        key_prefix=field_key_prefix,
    )

    with st.form(f"edit_form_{product['product_id']}"):
        form_data = _render_schema_driven_fields(
            prefill=product,
            key_prefix=field_key_prefix,
            custom_threshold_enabled=custom_threshold_enabled,
        )
        col1, col2 = st.columns(2)
        with col1:
            save_clicked = st.form_submit_button("💾 Save Changes", use_container_width=True)
        with col2:
            cancel_clicked = st.form_submit_button("Cancel", use_container_width=True)

    if cancel_clicked:
        st.session_state.pop(edit_key, None)
        st.rerun()

    if save_clicked:
        try:
            products_service.edit_product(store_id, product["product_id"], form_data)
            bump_cache_epoch()
            st.session_state.pop(edit_key, None)
            st.success("Product updated.")
            st.rerun()
        except ValidationError as error:
            st.error(str(error))


def _render_add_product_form() -> None:
    """Render the Add New Product form.

    Bug fix: does NOT use st.form(..., clear_on_submit=True). That
    parameter clears every widget inside the form as soon as it is
    submitted - success or failure alike, entirely inside Streamlit's
    own widget machinery, before this function's own code below ever
    gets a chance to check whether add_product() actually succeeded.
    That meant a validation failure (e.g. one required field left
    blank) silently wiped every field the store owner had already
    filled in, forcing them to retype the whole form. The form now
    only clears explicitly, via the same two-phase sentinel pattern
    _render_custom_threshold_checkbox already uses for the checkbox
    outside this form - and only on the success path below, so a
    validation failure leaves every already-entered field exactly as
    the user left it.
    """
    store_id = get_current_store_id()
    field_key_prefix = "add"

    # Success-path reset sentinel, checked before any widget below is
    # instantiated - see _clear_add_product_form_fields's docstring.
    _clear_add_product_form_fields(field_key_prefix)

    # Rendered before st.form opens - see _render_custom_threshold_checkbox's
    # docstring for why.
    custom_threshold_enabled = _render_custom_threshold_checkbox(
        existing_value=None,
        key_prefix=field_key_prefix,
    )

    with st.form("add_product_form"):
        form_data = _render_schema_driven_fields(
            prefill=None,
            key_prefix=field_key_prefix,
            custom_threshold_enabled=custom_threshold_enabled,
        )
        submitted = st.form_submit_button("➕ Add Product", use_container_width=True)

    if not submitted:
        return

    try:
        products_service.add_product(store_id, form_data)
        bump_cache_epoch()
        st.success(f"'{form_data.get('name')}' added successfully.")
        # The checkbox lives outside the form, so clear_on_submit does
        # not affect it. A direct session_state.pop() + st.rerun() does
        # NOT reliably reset it: Streamlit's rerun restores widget values
        # from session state before rendering, so if the key still exists
        # at the start of the next run the checkbox ignores its `value`
        # default and shows the old checked state.
        #
        # The fix is a two-phase sentinel: set a flag here, then in
        # _render_custom_threshold_checkbox (which runs BEFORE st.checkbox
        # is called on the next render) check for the flag, delete the
        # widget key, and clear the flag - so st.checkbox sees no existing
        # key and correctly falls back to value=False (unchecked).
        st.session_state["_reset_threshold_checkbox"] = True
        # Same two-phase sentinel, for the form's own fields (name,
        # batch, expiry, mrp, rate, gst_percent, minimum_stock_threshold)
        # - see _clear_add_product_form_fields.
        st.session_state["_reset_add_product_form"] = True
        st.rerun()
    except ValidationError as error:
        st.error(str(error))


def _clear_add_product_form_fields(key_prefix: str) -> None:
    """Reset every Add Product field widget to empty, but ONLY when the
    '_reset_add_product_form' sentinel is set (i.e. only right after a
    successful add_product() call - see _render_add_product_form).

    Must be called before _render_schema_driven_fields/st.form open on
    this render, same reasoning as _render_custom_threshold_checkbox's
    own sentinel: Streamlit restores each keyed widget's value from
    session_state before the script body runs, so a widget key must be
    removed before that widget is instantiated for its default (empty)
    value to actually show - popping it after rendering, or after
    st.rerun() fires, is too late.

    A validation failure (ValidationError from add_product) never sets
    this sentinel, so on that path every field widget's key is left
    exactly as the user typed it - nothing here runs, and
    _render_schema_driven_fields re-renders with the user's own values
    still in session_state, exactly as any other Streamlit widget
    normally behaves outside a clear_on_submit form.
    """
    if not st.session_state.pop("_reset_add_product_form", False):
        return
    for field in PRODUCT_FIELDS:
        st.session_state.pop(f"{key_prefix}_{field.key}", None)


def _render_custom_threshold_checkbox(existing_value, key_prefix: str) -> bool:
    """Render the 'use custom minimum stock level' checkbox.

    This MUST be called outside of st.form(...), not inside it. Widgets
    inside a form don't trigger a script rerun until the form's submit
    button is pressed - st.form's own documentation states all widget
    values are sent "in a batch" on submit. That batching is exactly
    why, before this fix, checking this box didn't reveal the number
    input until the user clicked Add/Save: the script simply hadn't
    rerun yet to know the checkbox had changed.

    Rendering this checkbox outside the form means Streamlit reruns the
    script the instant it's toggled, so the number input below (which
    reads this function's return value) appears or disappears
    immediately, before any submit button is touched.

    Session state reset note: after a successful Add Product save,
    _render_add_product_form sets a '_reset_threshold_checkbox' sentinel
    in session state. This function checks for that sentinel first -
    before st.checkbox is called - and if present, deletes the checkbox's
    own widget key and clears the sentinel, so st.checkbox falls back to
    value=False (its unchecked default). This is the only reliable
    pattern for resetting an outside-form widget value across a rerun
    boundary: modifying session_state after rerun() fires is too late,
    because Streamlit restores widget state from the existing key before
    the script body runs.

    Args:
        existing_value: The product's current minimum_stock_threshold,
            or None - used only to set the checkbox's initial state
            (checked if a custom value already exists), e.g. when
            opening Edit on a product that already has one set.
        key_prefix: Unique prefix for this checkbox's widget key, so the
            Add form and each product's Edit form don't collide.

    Returns:
        True if the store owner wants to set a custom threshold for
        this product, False to use the store-wide default.
    """
    widget_key = f"{key_prefix}_minimum_stock_threshold_enabled"

    if st.session_state.pop("_reset_threshold_checkbox", False):
        # Remove the widget's own key so st.checkbox below sees no
        # existing value and falls back to value=False (unchecked).
        st.session_state.pop(widget_key, None)

    return st.checkbox(
        "Set a custom minimum stock level for this product",
        value=existing_value is not None,
        key=widget_key,
    )


def _render_schema_driven_fields(prefill: dict, key_prefix: str, custom_threshold_enabled: bool) -> dict:
    """Render one input widget per field in PRODUCT_FIELDS, choosing the
    widget type from each field's FieldType, and return the collected
    raw values.

    This is the function that makes the form schema-driven: it contains
    no medicine-specific field names. Add Product and Edit Product both
    call this with different prefill data, so the two forms can never
    drift out of sync with each other or with product_schema.py.

    Must be called inside st.form(...) - unlike the checkbox above,
    these fields don't need to react to each other's changes within a
    single render, so batching them for submission is the right
    behavior (and is what makes "press Enter in one field" not
    prematurely submit the whole form).

    Args:
        prefill: Existing product dict to pre-fill values from (edit
            mode), or None for an empty form (add mode).
        key_prefix: Unique prefix for Streamlit widget keys, so the same
            field rendered in multiple forms (e.g. one expander per
            product) doesn't collide in session state.
        custom_threshold_enabled: The current state of the "use custom
            minimum stock level" checkbox, rendered separately (and
            earlier, outside the form) by
            _render_custom_threshold_checkbox. Passed in rather than
            rendered here so the checkbox can live outside the form and
            still control whether this function shows the number input.

    Returns:
        A dict of raw form values keyed by product_schema field keys,
        ready to pass into the service layer for validation. Includes
        an internal "_minimum_stock_threshold_enabled" key carrying the
        checkbox state through to the service layer's validation.
    """
    form_data = {"_minimum_stock_threshold_enabled": custom_threshold_enabled}

    for field in PRODUCT_FIELDS:
        widget_key = f"{key_prefix}_{field.key}"
        existing_value = prefill.get(field.key) if prefill else None
        label = field.label + ("" if field.required else " (optional)")

        if field.field_type == FieldType.DATE:
            if field.key == "expiry_date":
                # expiry_date is stored as MM/YY (e.g. "03/28", "Jun-2028")
                # after the OCR migration. Use a text input, not a date
                # picker — fromisoformat("1/29") crashes on these values.
                form_data[field.key] = st.text_input(
                    label,
                    value=existing_value or "",
                    key=widget_key,
                    placeholder="e.g. 03/28 or Jun-2028",
                )
            else:
                default_date = (
                    date.fromisoformat(existing_value) if existing_value else date.today()
                )
                form_data[field.key] = st.date_input(label, value=default_date, key=widget_key)

        elif field.field_type == FieldType.NUMBER:
            if field.key == "minimum_stock_threshold":
                # The checkbox itself is rendered OUTSIDE this form (see
                # _render_custom_threshold_checkbox) so toggling it
                # reruns the script immediately. By the time we get
                # here, custom_threshold_enabled already reflects that
                # rerun's result, so the number input below appears or
                # is skipped on the very same render - no extra click
                # needed.
                if custom_threshold_enabled:
                    # value=None (rather than defaulting to 1) means the
                    # widget shows genuinely empty when a user newly
                    # checks the box, instead of pre-filling a number
                    # that looks like a deliberate choice and could be
                    # submitted unchanged without the user ever having
                    # typed a real threshold. Validation of "is this
                    # blank/too-low" is deliberately deferred to Save -
                    # see service.py's _validate_and_clean_product_data.
                    default_threshold = float(existing_value) if existing_value else None
                    raw_threshold = st.number_input(
                        label,
                        min_value=1.0,
                        value=default_threshold,
                        step=1.0,
                        key=widget_key,
                        placeholder="Enter minimum stock level",
                    )
                    form_data[field.key] = raw_threshold
                else:
                    form_data[field.key] = None
            else:
                default_number = float(existing_value) if existing_value is not None else 0.0
                form_data[field.key] = st.number_input(
                    label, min_value=0.0, value=default_number, step=1.0, key=widget_key
                )

        elif field.field_type == FieldType.PERCENT:
            default_percent = float(existing_value) if existing_value is not None else 0.0
            form_data[field.key] = st.number_input(
                label, min_value=0.0, max_value=100.0, value=default_percent, step=0.5, key=widget_key
            )

        else:  # FieldType.TEXT
            form_data[field.key] = st.text_input(
                label, value=existing_value or "", key=widget_key
            )

    return form_data
